name: Import FoD SAST Results into Sigrid
on: 
 workflow_dispatch:
 push:
  tags:
   - '*'
permissions:
  contents: write
  
jobs:                                                  
  Export-FoD-To-repo:
    runs-on: ubuntu-latest
    permissions:
        actions: read
        contents: read
        security-events: write
    steps:
       - uses: actions/checkout@v3
       # Pull SAST issues from Fortify on Demand and generate GitHub-optimized SARIF output
       - name: Export Results from FoD
         uses: fortify/gha-export-vulnerabilities@v1
         with:
          export_config: ${{github.workspace}}/.sigrid/MyCustomExportConfig_FOD_Export.yml
          fod_base_url: "https://emea.fortify.com/"
          fod_tenant: ${{ secrets.FOD_TENANT }}
          fod_user: ${{ secrets.FOD_USER }}
          fod_password: ${{ secrets.FOD_PAT }}
          fod_release_id: ${{ secrets.FOD_RELEASE_ID }}
       - run: "mkdir -p .sigrid && mv ./fortify-sast.sarif .sigrid"
       #- name: Save results
       #  uses: actions/upload-artifact@master
       #  with:
       #     name: gh-fortify-sast.sarif
       #     path: ".sigrid"
       #     retention-days: 7
       #     if-no-files-found: ignore
       - name: Display structure of .sigrid files
         run: ls -R
         working-directory: .sigrid
       - name: Commit Fortify export to repository
         run: |
          git config --global user.name 'Fortify export'
          git add .sigrid/fortify-sast.sarif
          git commit -m "Automated fortify Sigrid export"
          git push
       - name: Download Sigrid CI
         run: "git clone https://github.com/Software-Improvement-Group/sigridci.git sigridci"
       - name: "Run Sigrid CI to upload" 
         env:
           SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"
         run: "./sigridci/sigridci/sigridci.py --customer sigdev --system webgoat-net --source . --publish"
