name: Import FoD SAST Results (SARIF format) into Sigrid (?)
on: 
 workflow_dispatch:
 push:
  tags:
   - '*'
      
jobs:                                                  
  Export-FoD-To-GitHub:
    runs-on: ubuntu-latest
    permissions:
        actions: read
        contents: read
        security-events: write
    steps:
       - uses: actions/checkout@v3
       # Pull SAST issues from Fortify on Demand and generate GitHub-optimized SARIF output
       - name: Export Results
         uses: fortify/gha-export-vulnerabilities@v1
         with:
          export_config: ${{github.workspace}}/.sigrid/MyCustomExportConfig_FOD_Export.yml
          fod_base_url: "https://emea.fortify.com/"
          fod_tenant: ${{ secrets.FOD_TENANT }}
          fod_user: ${{ secrets.FOD_USER }}
          fod_password: ${{ secrets.FOD_PAT }}
          fod_release_id: ${{ secrets.FOD_RELEASE_ID }}
       - name: Archive code coverage results
         uses: actions/upload-artifact@v3
         with:
           name: sarif-report
           path: gh-fortify-sast.sarif

       # Save results
       # Import Fortify SAST results to GitHub Security Code Scanning
       #- name: Import Results
       #  uses: github/codeql-action/upload-sarif@v2
       #  with:
       #   sarif_file: ./gh-fortify-sast.sarif